url: "{{- site.data.defaults.url }}"
permalink: /:title/
plugins:
  - jekyll-last-modified-at
markdown: kramdown
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "tailwind.config.js",
  "package.json",
  "package-lock.json",
  "postcss.config.js",
  "css",
  "node_modules",
  "examples",
  "runblog.sh",
  "build_images.sh",
  ".logo",
  ".cover"
]
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
